export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PRACTICE: '/practice',
  PRACTICE_DETAIL: '/practice/:testId',
  FULL_TEST: '/full-test',
  FULL_TEST_DETAIL: '/full-test/:testId',
  TEST_PREVIEW: '/tests/:testId',
  RESULTS: '/results',
  RESULT_DETAIL: '/results/:id',
  STATISTICS: '/statistics',
  PROFILE: '/profile',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:userId',
  ADMIN_QUESTIONS: '/admin/questions',
  ADMIN_TESTS: '/admin/tests',
  ADMIN_TEST_DETAIL: '/admin/tests/:testId',
};
